import random, time, webbrowser

from pynput.keyboard import Key, Controller
keyboard = Controller()
type = ["BAD", "UNCHECKED"]
numbers = ['a','b','c','d',"e","f","g","h","i","j","k","l","m","n","o","p","q","r","s","t","u","v","w","x","x","y","z","1","2","3","4","5","6","7","8","9"]
webpage = "https://ec.nintendo.com/redeem#/"

print(f"Press Enter To Begin")
input ("")
while True:
    time.sleep(3)
    random1 = random.choice(numbers)
    random2 = random.choice(numbers)
    random3 = random.choice(numbers)
    random4 = random.choice(numbers)
    random5 = random.choice(numbers)
    random6 = random.choice(numbers)
    random7 = random.choice(numbers)
    random8 = random.choice(numbers)
    random9 = random.choice(numbers)
    random10 = random.choice(numbers)
    random11 = random.choice(numbers)
    random12 = random.choice(numbers)
    random13 = random.choice(numbers)
    random14 = random.choice(numbers)
    random15 = random.choice(numbers)
    random16 = random.choice(numbers)
    web = webbrowser.open(f'{webpage}')
    time.sleep(5)
    keyboard.press(Key.tab)
    keyboard.release(Key.tab)
    keyboard.press(Key.enter)
    keyboard.release(Key.enter)
    keyboard.type(random1)
    keyboard.type(random2)
    keyboard.type(random3)
    keyboard.type(random4)
    keyboard.type(random5)
    keyboard.type(random6)
    keyboard.type(random7)
    keyboard.type(random8)
    keyboard.type(random9)
    keyboard.type(random10)
    keyboard.type(random11)
    keyboard.type(random12)
    keyboard.type(random13)
    keyboard.type(random14)
    keyboard.type(random15)
    keyboard.type(random16)
